### ISSUE TITLE
Python Interpreter Error: module has no attribute 

### ISSUE THREAD

**Issue by helincao** [modelstar-labs/modelstar#1]
See this error when running `> modelstar register example.py add_func`

To reproduce:
1) Clone the new repo, and update modelstar to 0.1.0 through `> poetry install`
2) Create a new modelstar proj: `>modelstar init test_1/`
3) Update project configs following the example on Notion:  https://www.notion.so/modelstar/Vault-secrets-Do-NOT-share-41527185cb584244b7fe3bd035a856b7#061515bcdc2f4c40b877dc22ae9e8113
4) Register `add()` in example.py using command `> modelstar register example.py add`, successfully.
5) Rename `add()` to `add_func()` in example.py, run register command `> modelstar register example.py add_func`. It showed the following error:
```Bash
(modelstar-py3.9) helix@PyWebIO test_1 % modelstar register example.py add_func
Registering `example.py` function... 
example.py check done.
/Users/helix/Documents/modelstar/modelstar/test_1/functions/example.py
("Python Interpreter Error:\nAttributeError: module 'example' has no attribute 'add_func' in function ADD_FUNC with handler example.add_func",)
```

6) If I do not rename `add()`, instead, just append a new func called `add_func()`, and run `> modelstar register example.py add_func`, no errors show up.

**Comment by helincao** [comment]
Step 6 seems to pass, however, history shows the function registered as UDF is still `add()`, not `add_func()`
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/18755763/188492941-7525608a-5e40-4d08-aa88-2c73f00b107d.png">

**Comment by krish-adi** [comment]
Added version control to re-upload changes in files.
